if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[P_LogTraceCassette_I]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[P_LogTraceCassette_I]
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO

CREATE PROCEDURE dbo.P_LogTraceCassette_I
	@ATM		varchar (10) ,
	@FUIB 		varchar (10) ,
	@Date 		datetime     ,
	@Time 		datetime     ,
	@DateTime 	datetime     ,
	@FileName	varchar (150),
	@Len 		varchar (10) ,
	@RSTA 		varchar (10) ,
	@RACT 		varchar (10) ,
	@RRET 		varchar (10) ,
	@1STA 		varchar (10) ,
	@1NUM 		varchar (10) ,
	@1CUR 		varchar (10) ,
	@1REL 		varchar (10) ,
	@1VAL 		varchar (10) ,
	@1LEN 		varchar (10) ,
	@1TOL 		varchar (10) ,
	@1ACT 		varchar (10) ,
	@1LOW 		varchar (10) ,
	@1L_D 		varchar (10) ,
	@1REJ 		varchar (10) ,
	@2STA 		varchar (10) ,
	@2NUM 		varchar (10) ,
	@2CUR 		varchar (10) ,
	@2REL 		varchar (10) ,
	@2VAL 		varchar (10) ,
	@2LEN 		varchar (10) ,
	@2TOL 		varchar (10) ,
	@2ACT 		varchar (10) ,
	@2LOW 		varchar (10) ,
	@2L_D 		varchar (10) ,
	@2REJ 		varchar (10) ,
	@3STA 		varchar (10) ,
	@3NUM 		varchar (10) ,
	@3CUR 		varchar (10) ,
	@3REL 		varchar (10) ,
	@3VAL 		varchar (10) ,
	@3LEN 		varchar (10) ,
	@3TOL 		varchar (10) ,
	@3ACT 		varchar (10) ,
	@3LOW 		varchar (10) ,
	@3L_D 		varchar (10) ,
	@3REJ 		varchar (10) ,
	@4STA 		varchar (10) ,
	@4NUM 		varchar (10) ,
	@4CUR 		varchar (10) ,
	@4REL 		varchar (10) ,
	@4VAL 		varchar (10) ,
	@4LEN 		varchar (10) ,
	@4TOL 		varchar (10)  ,
	@4ACT 		varchar (10)  ,
	@4LOW 		varchar (10)  ,
	@4L_D 		varchar (10)  ,
	@4REJ 		varchar (10)  ,
	@err		int	OUTPUT, 
	@Mess 		varchar(100) OUTPUT 

 AS
    insert
	LogTraceCassette(
	ATM		,
	FUIB 		,
	[Date] 		,
	[Time] 		,
	[DateTime] 	,
	[FileName]	,
	[Len] 		,
	[RSTA] 		,
	[RACT] 		,
	[RRET] 		,
	[1STA] 		,
	[1NUM] 		,
	[1CUR] 		,
	[1REL] 		,
	[1VAL] 		,
	[1LEN] 		,
	[1TOL] 		,
	[1ACT] 		,
	[1LOW] 		,
	[1L_D] 		,
	[1REJ] 		,
	[2STA] 		,
	[2NUM] 		,
	[2CUR] 		,
	[2REL] 		,
	[2VAL] 		,
	[2LEN] 		,
	[2TOL] 		,
	[2ACT] 		,
	[2LOW] 		,
	[2L_D] 		,
	[2REJ] 		,
	[3STA] 		,
	[3NUM] 		,
	[3CUR] 		,
	[3REL] 		,
	[3VAL] 		,
	[3LEN] 		,
	[3TOL] 		,
	[3ACT] 		,
	[3LOW] 		,
	[3L_D] 		,
	[3REJ] 		,
	[4STA] 		,
	[4NUM] 		,
	[4CUR] 		,
	[4REL] 		,
	[4VAL] 		,
	[4LEN] 		,
	[4TOL] 		,
	[4ACT] 		,
	[4LOW] 		,
	[4L_D] 		,
	[4REJ] 		
		)       
	VALUES
	(
	@ATM		,
	@FUIB 		,
	@Date 		,
	@Time 		,
	@DateTime 	,
	@FileName	,
	@Len 		,
	@RSTA 		,
	@RACT 		,
	@RRET 		,
	@1STA 		,
	@1NUM 		,
	@1CUR 		,
	@1REL 		,
	@1VAL 		,
	@1LEN 		,
	@1TOL 		,
	@1ACT 		,
	@1LOW 		,
	@1L_D 		,
	@1REJ 		,
	@2STA 		,
	@2NUM 		,
	@2CUR 		,
	@2REL 		,
	@2VAL 		,
	@2LEN 		,
	@2TOL 		,
	@2ACT 		,
	@2LOW 		,
	@2L_D 		,
	@2REJ 		,
	@3STA 		,
	@3NUM 		,
	@3CUR 		,
	@3REL 		,
	@3VAL 		,
	@3LEN 		,
	@3TOL 		,
	@3ACT 		,
	@3LOW 		,
	@3L_D 		,
	@3REJ 		,
	@4STA 		,
	@4NUM 		,
	@4CUR 		,
	@4REL 		,
	@4VAL 		,
	@4LEN 		,
	@4TOL 		,
	@4ACT 		,
	@4LOW 		,
	@4L_D 		,
	@4REJ 		
	)               
	                


	if @@rowcount<>1 begin
		select @Mess='Не могу добавить в БД' ,@err=1
		RaisError(@Mess,16,1)
		return 1
	end		
	select @Mess='Успешно!!!'
	select @err=0
	return 0
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

